<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <script src="<?= $wwwUrl ?>/js/calendar.js"></script>
    <script src="<?= $wwwUrl ?>/js/calendar2.js"></script>
    <script src="<?= $wwwUrl ?>/js/showTable.js"></script>
    <script src="<?= $wwwUrl ?>/js/main.js"></script>
    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <nav>
    <a href="<?=$requestUrl ?>/">Home</a>
    <a href="<?=$requestUrl ?>/menu">Menu</a>
    <a href="<?=$requestUrl ?>/reservation">Reservation</a>
    <a href="<?=$requestUrl ?>/register">Register</a>
    <a href="<?=$requestUrl ?>/login">Login</a>
    <a href="<?=$requestUrl ?>/logout">Logout</a>
    <a href="<?=$requestUrl ?>/user">User Account</a>
    </nav>
</header>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <small>This is footer <i class="fa fa-heart"></i>&nbsp; Nothing in it</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>