<div>
<h1>Welcome <?= $session->getFirstName();?> <?= $session->getLastName();?> !!!</h1>
<div class="left">
<img src="" alt="">
</div>
<div class="right">
<div class="email">email : <?= $session->getEmail(); ?></div>
<div class="tel">tel : <?= $session->getTel(); ?></div>
<div class="adress">adresse : <?= $session->getStreet();?>
<?= $session->getCodePostal(); ?> 
<?= $session->getCity(); ?></div>
<?= $session->getUserId();?>
<form action="" method="post">
<button type="submit" name="editAccount" class="edit" value="<?= $session->getUserId();?>">edit my account</button>
</form>

<a href="<?=$requestUrl ?>/user/edit">Edit </a>

<button type="submit" name="deleteAccount" class="delete" value="<?= $session->getUserId();?>">delete my account</button>
</div>
</div>