<div class="menu">
<section class="entree">
    <!--<h1>SELECTION OF ENTRE</h1>
    <div class="flex">
        <?php if(isset($entree)): ?>
        <?php //var_dump($entree); ?>
        <?php foreach($entree as $entre): ?>

        <article>       
            <h3><?= $entre['product_name']; ?></h3>
            <img src="" alt="">
            <p>Price:<?= $entre['price']; ?>Euros</p>
            <button>Ajoute</button>
        </article>

        <?php endforeach; ?>
        <?php endif; ?>
        </div>
</section>
<section class="plat">
    <h1>SELECTION OF PLATES</h1>
    <div class="flex">
        <?php if(isset($plates)): ?>
        <?php //var_dump($entree); ?>
        <?php foreach($plates as $plate): ?>

        <article>       
            <h3><?= $plate['product_name']; ?></h3>
            <img src="" alt="">
            <p>Price:<?= $plate['price']; ?>Euros</p>
            <button>Ajoute</button>
        </article>

        <?php endforeach; ?>
        <?php endif; ?>
        </div> -->


    <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 font-italic">Selection of entreee</h1>
        <p class="lead my-3">Nasze menu jest najlepsze, zaprasamy do wizyty. smaczne jedzenie.</p>
    </div>
    </div>

    <div class="flex">
        <?php if(isset($entree)): ?>
        <?php //var_dump($entree); ?>
        <?php foreach($entree as $entre): ?>


    <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">Entree</strong>
              <h3 class="mb-0">
                <a class="text-dark" href="#"><?= $entre['product_name']; ?></a>
              </h3>
              <div class="mb-1 text-muted"><?= $entre['price']; ?> Euros</div>
              <p class="card-text mb-auto"><?= $entre['product_description']; ?></p>
              <a href="#">Add</a>
            </div>
            <img class="card-img-right flex-auto d-none d-md-block" src="<?= $wwwUrl ?>/images/entree/001.jpeg" alt="Card image cap">
          </div>
        </div>

<?php endforeach; ?>
        <?php endif; ?>
        </div>
    
</section>
<section class="dessert">
</section>
</div>