<div class="menu">
<h1>Menu !!!</h1>
<h2>Selection of categories</h2>
<section class="category">
    <div>  
        <?php if(isset($categories)): ?>
        <?php //var_dump($categories); die; ?>
        <?php foreach($categories as $category): ?>
        <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
                <h1 class="display-4 font-italic"><?= $category['category_name']; ?></h1>
                <p class="lead my-3"><?= $category['category_description']; ?></p>
                <a href="<?=$requestUrl ?>/menu/<?= $category['category_name']; ?>">Check cart for <?= $category['category_name']; ?> </a>
            </div>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>        
    </div>
</secttion>
</div>