<h1>register view</h1>

<?php 
if(isset($message))
{
    echo $message;
}
?>

<form action="" method="post">

first name <input name="first_name" type="text"> <br>
last name <input name="last_name" type="text"> <br>
email <input name="email" type="email"> <br>
password <input name="password" type="password"> <br>
password <input name="password2" type="password"> <br>
street<input name="street" type="text"> <br>
city<input name="city" type="text"> <br>
code postal<input name="code_postal" type="text"> <br>
tel <input name="tel" type="text"> <br>
<input type="submit" value="Register">

</form>